### ISSUE TITLE
Why is `ignoreFile` set to `const False`? For me this resulted in emacs temp files not being ignored in testing

### ISSUE THREAD

**Issue by cxandru** [rpearce/hakyll-nix-template#23]
https://github.com/rpearce/hakyll-nix-template/blob/9a03eb23a6e7f7e0827679cf01d3ceda667b3c46/ssg/src/Main.hs#L35

I'm following the instructions as per the readme. I originally expected https://github.com/rpearce/hakyll-nix-template/blob/9a03eb23a6e7f7e0827679cf01d3ceda667b3c46/haskell-overlay.nix#L47 to be enough, but I guess it isn't. Perhaps for the initial `nix build` But I guess it _can't_ really work for live rebuilding anyway. So my question is, why set this to `const False` in the template and have Emacs users run into problems?

**Comment by rpearce** [comment]
I use vim/neovim, but I have it set up to put all my swap files in a certain system directory that isn't the current one, so I don't run in to this.

If this doesn't work for you, I would try commenting that line out.

As you can see from the source, https://github.com/jaspervdj/hakyll/blob/4086d0d87c8ff2327f250ed67ff65d1ea5c14fb1/lib/Hakyll/Core/Configuration.hs#L97-L120, it performs some checks and returns a Bool (see `ignoreFile'`). If you want those checks, then by all means restore the original functionality.

It might be worth me not including that in this template... I'll think on it.

**Comment by rpearce** [comment]
This will be resolved in https://github.com/rpearce/hakyll-nix-template/pull/37
