### ISSUE TITLE
Build fails due to simple-sendfile

### ISSUE THREAD

**Issue by sofia-m-a** [rpearce/hakyll-nix-template#25]
I get an error when building the simple-sendfile dependency. Seems to be related to https://github.com/kazu-yamamoto/simple-sendfile/issues/17. I'm not sure how to disable the checking; simple-sendfile is a Hakyll dependency and `dontCheck` is already set for Hakyll? Does that not apply to dependencies?

**Comment by rpearce** [comment]
Bummer. I don't know the answer to that, and I'll need to dig into this when I get time. It will take a few days.

On the plus side, I may be better able to pin down hakyll and such.

**Comment by rpearce** [comment]
I'm having my own issues trying to run this on my new Apple M1 and am working to find a way to get this to build 😞

**Comment by rpearce** [comment]
@sofia-m-a I've finally fixed the build over on another project and will port those over here once I'm done.

**Comment by rpearce** [comment]
This should be fixed now. Let me know if it's not!
