### ISSUE TITLE
Problem building `cwf-ssg-exe-hakyll-site` with Nix

### ISSUE THREAD

**Issue by kutyel** [rpearce/hakyll-nix-template#42]
Yesterday I run `run nix . watch` and it was working correctly, today it does not work :S
```sh
error: builder for '/nix/store/qhs8gcbas45hmliwpik01qz0rffz2cwf-ssg-exe-hakyll-site-0.1.0.0.drv' failed with exit code 1;
       last 10 log lines:
       >   |
       > 6 | import Data.Text qualified as T
       >   |                  ^^^^^^^^^
       >
       > src/Main.hs:7:26: error:
       >     Found ‘qualified’ in postpositive position.
       >     To allow this, enable language extension 'ImportQualifiedPost'
       >   |
       > 7 | import Data.Text.Slugger qualified as Slugger
       >   |                          ^^^^^^^^^
       For full logs, run 'nix log /nix/store/qhs8gcbas45hmliwpik01qz0rffz2cwf-ssg-exe-hakyll-site-0.1.0.0.drv'.
```

**Comment by rpearce** [comment]
I believe these should be

```
import qualified ...
```

Can you try moving the `qualified` to just after the import?

Also, hi! I follow you on Twitter

**Comment by kutyel** [comment]
Gracias! Sí, tenía configurado fourmolu con el `ImportQualifiedPost` por el trabajo y el proyecto no tenía esa extensión en el cabal file, perdón por abrir una issue para un problema tan tonto 😓 

El CSS de tu site me parece muy minimalista y muy bien elegido, se parece al tema por defecto de Gatsby, algún consejo para poder copiarlo con facilidad? He tratado de copiar el JS y el CSS pero estoy teniendo [problemas con Cachix](https://github.com/kutyel/kutyel-hakyll/actions/runs/4234035169/jobs/7355783738) y nada parece funcionar 😭

**Comment by rpearce** [comment]
Para cachix, ¿tienes un token de acceso que está en la configuración de tu repositorio como la descripción en mi tutorial?

https://robertwpearce.com/the-hakyll-nix-template-tutorial.html

Busca para `CACHIX_AUTH_TOKEN`.

* * *

Sobre el CSS, todo el sitio fue escrito por mi. También, ¡estoy cambiando todo el diseño pronto! Sin embargo, si desea copiar el codigo, aquí está:

* https://github.com/rpearce/robertwpearce.com/tree/main/src/css
* https://github.com/rpearce/robertwpearce.com/blob/main/src/js/source/index.ts

Pero la compilación de JS no es excelente. Es más fácil a incluir el JS en un elemento de `<script>`.

**Comment by kutyel** [comment]
Estaba usando mi caché personal de cachix con `kutyel` y añadí el `CACHIX_AUTH_TOKEN` como ponía en tu blogpost (muy bueno por cierto y muchas gracias por hacerlo! 👏🏻 ). Pero eso no funcionaba, así que cree una caché nueva en cachix llamada kutyel-hakyll con un nuevo par de signing keys y cambié la variable para el CI a `CACHIX_SIGNING_KEY` (como sugiere el mensaje de error del CI), pero eso tampoco funciona 😭

**Comment by rpearce** [comment]
## En Español

El error de https://github.com/kutyel/kutyel-hakyll/actions/runs/4234035169/jobs/7355783738 es

```default
No narinfo signature found. Is $CACHIX_SIGNING_KEY set? To generate one, run `cachix generate-keypair`
```

No sé nada sobre este error, ¿pero creaste un token en esta página? https://app.cachix.org/personal-auth-tokens

Por ejemplo, tengo un token se llama `robertwpearce-com-gh` para GitHub que usé en esta pagina, https://github.com/rpearce/hakyll-nix-template/settings/secrets/actions, y lo llamé `CACHIX_AUTH_TOKEN` (se utiliza aqui: https://github.com/rpearce/hakyll-nix-template/blob/9a4b698d68996f5a40c3f55ad5ba1fa90972b17b/.github/workflows/main.yml#L29)

Tu pagina es https://github.com/kutyel/kutyel-hakyll/settings/secrets/actions

## In English

The error from https://github.com/kutyel/kutyel-hakyll/actions/runs/4234035169/jobs/7355783738 is

```default
No narinfo signature found. Is $CACHIX_SIGNING_KEY set? To generate one, run `cachix generate-keypair`
```

I don't know anything about this error, but did you create a token on this page? https://app.cachix.org/personal-auth-tokens

For example, I have a token called `robertwpearce-com-gh` for GitHub that I used on this page, https://github.com/rpearce/hakyll-nix-template/settings/secrets/actions, and I called it `CACHIX_AUTH_TOKEN` (it is used here https://github.com/rpearce/hakyll-nix-template/blob/9a4b698d68996f5a40c3f55ad5ba1fa90972b17b/.github/workflows/main.yml#L29).

Your page is https://github.com/kutyel/kutyel-hakyll/settings/secrets/actions

**Comment by rpearce** [comment]
Estoy in Nueva Zelanda por una semana más, y necesito dormir. ¡Hasta mañana!

* * *

I am in New Zealand for one more week, and I need to sleep. Until tomorrow!
